name: Deploy Website

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Pull latest code
        run: |
            cd ~/first_server_rep
            git pull origin main
      - name: Deploy with Docker Compose
        run: |
            cd ~/first_server_rep
            docker compose up -d --force-recreate